config/routes.rb
Rails.application.routes.draw do
  resources :session, only: [:new, :create]
  get 'exit', to: 'session#logout', as: :logout

  namespace :loja do
    root :to => 'home#index', as: :loja
    resources :usuarios
    resources :vendas
  end

  resources :categorias
  resources :produtos

  get 'painel', to: 'painel#index', as: :painel
end

app/views/shared/_breadcrumb.html.erb
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to "Home", loja_loja_path %>
    </li>
    <li class="breadcrumb-item active" aria-current="page"><%= categoria %></li>
  </ol>
</nav>

app/views/shared/_card_produto.html.erb
<div class="col-md-3">
  <div class="card">
    <img src="product_default.png" class="card-img-top" alt="...">
    <div class="card-body">
      <h4 class="card-title">
        <%= produto.descricao %>
      </h4>
      <p class="text-danger">
        <%= number_to_currency(produto.preco, unit: "R$ ", separator: ",", delimiter: "") %>
      </p>
      <%= link_to "Comprar", edit_produto_path(produto), class: "btn btn-danger text-light" %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Menu</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to "Home", loja_loja_path, class: 'nav-link active' %>
      </div>
    </div>
    <div class="d-flex">
      <% if usuario_atual %>
        <%= link_to "Editar conta", edit_loja_usuario_path(usuario_atual), class: 'nav-link' %>
        <%= link_to "Logout", logout_path, class: 'nav-link' %>
      <% else %>
        <%= link_to "Login", new_session_path, class: 'nav-link' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_validation.html.erb
<% if flash[:notice] %>
  <div class="alert alert-warning" role="alert">
    <%= flash[:notice].html_safe %>
  </div>
<% end %>