config/routes.rb
Rails.application.routes.draw do
  resources :session, only: [:new, :create]
  get 'exit', to: 'session#logout', as: :logout

  namespace :loja do
    root :to => 'home#index', as: :loja
    resources :usuarios
    resources :vendas
  end

  resources :categorias
  resources :produtos

  get 'painel', to: 'painel#index', as: :painel
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_many :vendas
  validates :senha, length: { minimum:5 }
end

app/controllers/loja/detalhes_venda_controller.rb
class Loja::DetalhesVendaController < ApplicationController
  def new
    @venda = Venda.new
    render :new
  end

  def carrinho
    @itens = Produto.where() 
  end

  def create
    venda = Venda.new(usuario_id: params[:usuario_id])
  end

  private

  def set_venda
    @venda = Venda.find params[:venda_id]
  end
end

app/controllers/loja/home_controller.rb
class Loja::HomeController < LojaController
  def index
    @produtos = Produto.all
  end
end

app/controllers/loja/usuarios_controller.rb
class Loja::UsuariosController < LojaController
  before_action :set_usuario, only: %i[ show edit update destroy ]

  def index
    @usuarios = Usuario.all
  end

  def show
  end

  def new
    @usuario = Usuario.new
  end

  def edit
  end

  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to loja_usuario_path(@usuario), notice: "Usuario cadastrado com sucesso!" }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: "Usuario atualizado com sucesso!" }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @usuario.destroy
    session[:usuario_id] = nil
    respond_to do |format|
      format.html { redirect_to new_session_path, notice: 'Usuario foi removido com sucesso!' }
      format.json { head :no_content }
    end
  end

  private

  def set_usuario
    @usuario = Usuario.find(params[:id])
  end

  def usuario_params
    params.require(:usuario).permit(:nome, :email, :endereco, :login, :senha, :administrador)
  end
end

app/controllers/loja/vendas_controller.rb
class Loja::VendasController < ApplicationController
  before_action :set_venda, only: %i(destroy show)

  def index
    @vendas = Venda.all
  end

  def show
    render :show
  end

  def destroy
    if @venda.detalhes_vendas
      @venda.detalhes_vendas.destroy_all
      @venda.destroy
      respond_to do |format|
        format.html { redirect_to painel_path, notice: "Venda foi removida!" }
        format.json { head :no_content }
      end
    end
  end

  private

  def set_venda
    @venda = Venda.find(params[:id])
  end
end

app/controllers/loja_controller.rb
class LojaController < ActionController::Base
  layout 'loja'
  helper_method :usuario_atual

  def usuario_atual
    Usuario.find(session[:usuario_id]) if session[:usuario_id]
  end

  def usuario_atual?(usuario)
    usuario_atual.id == usuario.id
  end
end

app/controllers/usuario_backoffice/usuarios_controller.rb
class UsuarioBackoffice::UsuariosController < UsuarioBackofficeController
  before_action :set_usuario, only: %i[ show edit update destroy ]

  def index
    @usuarios = Usuario.all
  end

  def show
  end

  def new
    @usuario = Usuario.new
  end

  def edit
  end

  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: "Usuario was successfully created." }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    def usuario_params
      params.require(:usuario).permit(:nome, :email, :endereco, :login, :senha, :administrador)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: %i[ show edit update destroy ]

  # GET /usuarios or /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: "Usuario was successfully created." }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:nome, :email, :endereco, :login, :senha, :administrador)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/loja/usuarios/_form.html.erb
<div class="row">
  <%= form_with(model: [:loja, @usuario]) do |form| %>
    <% if usuario.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

        <ul>
          <% usuario.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="col-md-6 mb-3">
      <%= form.label :nome, class: "form-label" %>
      <%= form.text_field :nome, class: "form-control" %>
    </div>

    <div class="col-md-6 mb-3">
      <%= form.label :email, class: "form-label" %>
      <%= form.text_field :email, class: "form-control" %>
    </div>

    <div class="col-md-6 mb-3">
      <%= form.label :endereco, class: "form-label" %>
      <%= form.text_field :endereco, class: "form-control" %>
    </div>

    <div class="col-md-6 mb-3">
      <%= form.label :login, class: "form-label" %>
      <%= form.text_field :login, class: "form-control" %>
    </div>

    <div class="col-md-6 mb-3">
      <%= form.label :senha, class: "form-label" %>
      <%= form.password_field :senha, class: "form-control" %>
    </div>

    <div class="col-md-6 mb-3">
      <%= form.label :administrador, class: "form-label" %>
      <%= form.check_box :administrador %>
    </div>

    <div class="actions">
      <%= form.submit "Submeter", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/loja/usuarios/edit.html.erb
<div class="container d-flex flex-column">
  <div class="justify-content-center">
    <div class="row">
      <h2 class="mt-4">Editar Usuário</h2>
    </div>

    <%= render 'form', usuario: @usuario %>

    <%= link_to 'Exibir', loja_usuario_path(@usuario) %> |
    <%= link_to 'Voltar', edit_loja_usuario_path %>
    <%= link_to 'Remover conta', loja_usuario_path(@usuario), method: :delete %>
  </div>
</div>

app/views/loja/usuarios/index.html.erb
<div class="container d-flex flex-column">
  <div class="justify-content-center">
    <div class="row">
      <p id="notice"><%= notice %></p>
    </div>

    <div class="row">
      <h2 class="mt-4">Usuários</h2>
    </div>

    <table>
      <thead>
        <tr>
          <th>Nome</th>
          <th>Email</th>
          <th>Endereco</th>
          <th>Login</th>
          <th>Administrador</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @usuarios.each do |usuario| %>
          <tr>
            <td><%= usuario.nome %></td>
            <td><%= usuario.email %></td>
            <td><%= usuario.endereco %></td>
            <td><%= usuario.login %></td>
            <td><%= usuario.administrador %></td>
            <td><%= link_to 'Exibir', loja_usuario_path(usuario), class: 'btn btn-info' %></td>
            <td><%= link_to 'Editar', edit_loja_usuario_path(usuario), class: 'btn btn-info' %></td>
            <td><%= link_to 'Remover', loja_usuario_path(usuario), method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-warning' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Novo Usuario', new_loja_usuario_path, class: 'btn btn-primary text-white' %>
  </div>
</div>

app/views/loja/usuarios/new.html.erb
<div class="container d-flex flex-column">
  <div class="justify-content-center">
    <div class="row">
      <h2 class="mt-4">Novo Usuário</h2>
    </div>

    <%= render 'form', usuario: @usuario %>

    <div class="row">
      <div class="col-md-3">
        <%= link_to 'Voltar', loja_usuarios_path, class: "btn btn-info" %>
      </div>
    </div>
  </div>
</div>

app/views/loja/usuarios/show.html.erb
<div class="container d-flex flex-column">
  <div class="justify-content-center">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Nome:</strong>
      <%= @usuario.nome %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @usuario.email %>
    </p>

    <p>
      <strong>Endereco:</strong>
      <%= @usuario.endereco %>
    </p>

    <p>
      <strong>Login:</strong>
      <%= @usuario.login %>
    </p>

    <p>
      <strong>Administrador:</strong>
      <%= @usuario.administrador %>
    </p>

    <%= link_to 'Editar', edit_loja_usuario_path(@usuario) %> |
  </div>
</div>