config/routes.rb
Rails.application.routes.draw do
  resources :session, only: [:new, :create]
  get 'exit', to: 'session#logout', as: :logout

  namespace :loja do
    root :to => 'home#index', as: :loja
    resources :usuarios
    resources :vendas
  end

  resources :categorias
  resources :produtos

  get 'painel', to: 'painel#index', as: :painel
end

app/models/produto.rb
class Produto < ApplicationRecord
  has_many :categorias_produtos
  has_many :categorias, through: :categorias_produtos
  has_many :detalhes_vendas
  has_many :vendas, through: :detalhes_vendas
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: %i[ show edit update destroy ]

  # GET /produtos or /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1 or /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos or /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: "Produto was successfully created." }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1 or /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: "Produto was successfully updated." }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1 or /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: "Produto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produto_params
      params.require(:produto).permit(:descricao, :preco, :foto, :quantidade)
    end
end

app/controllers/usuario_backoffice/produtos_controller.rb
class UsuarioBackoffice::ProdutosController < UsuarioBackofficeController
  before_action :set_produto, only: %i[ show edit update destroy ]

  # GET /produtos or /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1 or /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos or /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: "Produto was successfully created." }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1 or /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: "Produto was successfully updated." }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1 or /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: "Produto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produto_params
      params.require(:produto).permit(:descricao, :preco, :foto, :quantidade)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_with(model: produto) do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
        <% produto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :preco %>
    <%= form.text_field :preco %>
  </div>

  <div class="field">
    <%= form.label :foto %>
    <%= form.text_field :foto %>
  </div>

  <div class="field">
    <%= form.label :quantidade %>
    <%= form.number_field :quantidade %>
  </div>

  <div class="actions">
    <%= form.submit "Submeter", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<div class="container d-flex flex-column">
  <div class="justify-content-center">
    <div class="row">
      <h2 class="mt-4">Editar Produto</h2>
    </div>

    <%= render 'form', produto: @produto %>

    <%= link_to 'Exibir', @produto %> |
    <%= link_to 'Voltar', produtos_path %>
    <%= link_to 'Remover produto', produto_path(@produto), method: :delete %>
  </div>
</div>

app/views/produtos/index.html.erb
<div class="container d-flex flex-column">
  <div class="justify-content-center">
    <div class="row">
      <p id="notice"><%= notice %></p>
    </div>

    <h1>Produtos</h1>

    <table>
      <thead>
        <tr>
          <th>Descrição</th>
          <th>Preco</th>
          <th>Foto</th>
          <th>Quantidade</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @produtos.each do |produto| %>
          <tr>
            <td><%= produto.descricao %></td>
            <td><%= produto.preco %></td>
            <td><%= produto.foto %></td>
            <td><%= produto.quantidade %></td>
            <td><%= link_to 'Exibir', produto %></td>
            <td><%= link_to 'Editar', edit_produto_path(produto) %></td>
            <td><%= link_to 'Remover', produto, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Novo Produto', new_produto_path %>
  </div>
</div>

app/views/produtos/new.html.erb
<h1>Novo Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Voltar', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @produto.descricao %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @produto.preco %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @produto.foto %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @produto.quantidade %>
</p>

<%= link_to 'Edit', edit_produto_path(@produto) %> |
<%= link_to 'Back', produtos_path %>