config/routes.rb
Rails.application.routes.draw do
  resources :session, only: [:new, :create]
  get 'exit', to: 'session#logout', as: :logout

  namespace :loja do
    root :to => 'home#index', as: :loja
    resources :usuarios
    resources :vendas
  end

  resources :categorias
  resources :produtos

  get 'painel', to: 'painel#index', as: :painel
end

app/controllers/painel_controller.rb
class PainelController < ApplicationController
  before_action :verify_admin

  # GET /categoria or /categoria.json
  def index
    @usuario = Usuario.find(session[:usuario_id])
  end

  private

  def verify_admin
    usuario = Usuario.find(session[:usuario_id])

    unless usuario.administrador?
      session[:usuario_id] = nil
      redirect_to new_session_path, notice: 'Acessado negado!'
    end
  end
end

app/views/painel/index.html.erb
<div class="container">
  <div class="mt-3">
    <% if flash[:success] %>
      <div class="alert alert-success" role="alert">
        <%= flash[:success].html_safe %>
      </div>
    <% end %>

    <%= link_to "Editar conta", edit_loja_usuario_path(@usuario) %>

    <div class="section-product">
      <div class="row">
        <h2 class="mt-4">CRUD de Produtos</h2>
      </div>

      <%= link_to "Painel de Produtos", produtos_path %>
    </div>

    <div class="section-category">
      <div class="row">
        <h2 class="mt-4">CRUD de Categorias</h2>
      </div>

      <%= link_to "Painel de Categorias", categorias_path %>
    </div>

    <div class="section-product">
      <div class="row">
        <h2 class="mt-4">Gestão de compras</h2>
      </div>

      <%= link_to "Relatório de compras", loja_vendas_path %>
    </div>
  </div>
</div>